# Generated by Django 5.2.13 on 2026-05-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_is_premium'),
        ('accounts', '0008_remove_post_image_post_image_url'),
    ]

    operations = [
    ]
