# Generated by Django 5.2.13 on 2026-05-12 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260511_1357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cosmetic', 'Cosmetic'), ('subscription', 'Subscription'), ('real_world', 'Real World')], max_length=20)),
                ('effect', models.CharField(blank=True, max_length=50)),
                ('cost', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('color', models.CharField(default='oklch(0.6 0.22 255)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'cost'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClaimedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_at_claim', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=200)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='accounts.reward')),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='accounts.reward')),
            ],
        ),
    ]
