# Generated by Django 5.2.13 on 2026-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
