# Generated by Django 5.2.13 on 2026-05-14 05:28
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_seed_rewards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimedreward',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
        migrations.RemoveField(
            model_name='reward',
            name='order',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='selfie_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='claimedreward',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='claimedreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.reward'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reward',
            name='effect',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.CharField(blank=True, default='🎁', max_length=10),
        ),
        migrations.AlterField(
            model_name='rewardcode',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]