# Generated by Django 5.2.13 on 2026-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_claimedreward_is_equipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
