# Generated by Django 5.2.13 on 2026-05-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_claimedreward_options_alter_reward_options_and_more'),
        ('accounts', '0015_loop_image_url'),
    ]

    operations = [
    ]
